language: cpp

git:
  depth: false

matrix:
    include:

        ## OSX 10.12 - xcode 8.2 - Python 3.6
        - os: osx
          osx_image: xcode9.4
          compiler: clang
          env: >
            [
            CXX_COMPILER=clang++ ,
            C_COMPILER=clang     ,
            PYTHON_VERSION=3.6   ,
            ]
notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

cache:
  - ccache
  - $HOME/.pyenv

before_install:
  - export CC="$C_COMPILER"
  - export CXX="$CXX_COMPILER"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PREFIX="/usr/local"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ccache; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PYTHON_CONFIGURE_OPTS="--enable-shared --enable-unicode=ucs2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv root; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pyenv install --list  ;fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then pyenv install 3.5.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.6" ]]; then pyenv install 3.6.0; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then export PYTHON_INCLUDE_DIR=$(pyenv root)/versions/3.5.0/include/python3.5m ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then export PYTHON_LIBRARY=$(pyenv root)/versions/3.5.0/lib/libpython3.dylib   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.5" ]]; then export PYTHON_BINARY=$(pyenv root)/versions/3.5.0/bin/python3.5           ;fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.6" ]]; then export PYTHON_INCLUDE_DIR=$(pyenv root)/versions/3.6.0/include/python3.6m ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.6" ]]; then export PYTHON_LIBRARY=$(pyenv root)/versions/3.6.0/lib/libpython3.dylib   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON_VERSION" == "3.6" ]]; then export PYTHON_BINARY=$(pyenv root)/versions/3.6.0/bin/python3.6           ;fi

  - $PYTHON_BINARY -m pip install --upgrade pip
  - $PYTHON_BINARY -m pip install sphinx
  - $PYTHON_BINARY -m pip install --upgrade wheel
  - $PYTHON_BINARY -m pip install --upgrade setuptools


script:
  - $PYTHON_BINARY ./setup.py --static-jvm build -j8 install
  - $PYTHON_BINARY ./setup.py --static-jvm bdist_wheel
  - $PYTHON_BINARY ./examples/jadx_decompile.py ./examples/com.passwordchecker.apk --classes com.example.passwordchecker.PasswordChecker

deploy:
  provider: pypi
  user: pyjadx
  #server: https://test.pypi.org/legacy/
  distributions: "bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: Q1KSN6TjNGo+LjMswlQetdVglQr8Zo05ybew/7onwGu7TeuWx4HnQgyFbFilEhHpusPZdo+hE+utoOnmcuKyijyvzUHcF9eINShCs18rpdpanURTyfjef9N8d96ZeaJtkZPjwxIl23YjgQzxja6ubYgKwysDrrCut92Od+VMYu1XDFAU2jCUqMg4xTBCsMQTRq4MrAZE95jY0lJE3EyS3tAoFPOh3ur4ZIlnTJs6hWschDT0C7QQqJKAVSgENm4vlh4W/zuL/+zrIMu+1FBYG0GN3HvEiKNtgMF4ad19U/dvWcw5d863u3DwbmRToep1R0+hj9KX3gLK1smQfok7xWy0HAzmW/XTL55yB+1nbPJXi/EpgflItO4B/Ah6WUc2h+0mv0pLjPTHJuWRF0a3tQw1XtICBuT3lxVxwD0DSdutfOzbFRKf3MDmg15NZJ3Johb3EtVoZbkpAmweh/EYSvpQihqaSEg0g1/yInWb1nDyhfnZvvMvKgeAj7uxdoSPlSzicDWiD6SVemPxe8cT3pWTtbCc/KQbZAEHP0ADSG4A5Cxfj0UhGNCeGnQHCZfktos2gLk2ElXOfpVSX8Rc6sgDkLKaBBmWZmM9v2Zo8v0XOFMm43OhNpb11GTd6Srew9XrDot8qPb+6Ib+Ao1VBuN8PCHe//noyVBhsxeaWxk=
